micronaut:
  executors:
    io:
      type: cached
      nThreads: 75
  http:
    client:
      read-timeout: 25m
      read-idle-timeout: 25m
      num-of-threads: 25

  application:
    name: crfa-dapp-store-service

  server:
    port: 8080
    netty:
      access-logger:
        enabled: true

dryRunMode: false
env: dev
dbPath-dapps: crfa-dapp-store-dapps-dev.db
blockfrost-projectId: mainnetS6e1C6yuxQNHOX8SwVNHPvomtpOdD5Iu
redis-host: localhost
#redis-host: kajka.lan

jackson:
  serialization-inclusion: NON_ABSENT # Omit null and Optional.empty(), but include empty collections
  serialization:
    indent-output: true # Pretty-print JSON

